apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 50Gi
  storageClassName: "nfs-client"
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: 192.168.100.250
    path: /mnt
    readOnly: no
