apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    role: blackbox-rules
    app: kube-prometheus-stack
  name: prometheus-blackbox
  namespace: monitoring
spec:
  groups:
    - name: blackbox-rules
      rules:
        - alert: BlackProbeSuccess
          expr: probe_success == 0
          for: 2m
          labels:
            severity: "critical"
          annotations:
            summary: "Sur le Job {{ $labels.job }}, il semble que {{ $labels.instance }} ne reponde pas"
